swagger: '2.0'
info:
  version: '2.0'
  title: 'Freight booking API'
  description: 'This is an API detailing a freight booking delivery'
paths:
  /booking_details:
    post:
      summary: report on booking for delivery
      operationId: app.booking_details
      description: Records the details for customer delivery
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: deliveryDetails
        description: Details of delivery
        schema:
          $ref: '#/definitions/DeliveryDetails'
      responses:
        201:
          description: item added
        400:
          description: invalid input, object invalid
  /freight_assignment:
    post:
      summary: report on freight used for delivery
      operationId: app.freight_assignment
      description: Records the details for freights used for booking deliveries
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: freightAssignment
        description: Details of freight trailer used
        schema:
          $ref: '#/definitions/FreightAssignment'
      responses:
        201:
          description: item added
        400:
          description: invalid input, object invalid
definitions:
  DeliveryDetails:
    type: object
    required:
    - customer_id
    - delivery_id
    - pickup
    - destination
    - delivery_weight_in_pounds
    - delivery_dimensions_in_feet
    - timestamp
    properties:
      customer_id:
        type: string
        example: ahl2020-0000001-henrydrilling
      delivery_id:
        type: string
        example: ahl2020-0000001-vancal
      pickup:
        type: string
        example: Vancouver, BC L6J8N2
      destination:
        type: string
        example: Calgary, AB T1X0L3
      delivery_weight_in_pounds:
        type: integer
        example: 2000
      delivery_dimensions_in_feet:
        type: string
        example: 20 x 20 x 20
      timestamp:
        type: string
        format: date-time
        example: 2020-01-01T08:00:00.000Z


  FreightAssignment:
    type: object
    required:
    - freight_company
    - freight_id
    - freight_type_in_feet
    - max_weight_in_pounds
    - freight_load
    - timestamp
    properties:
      freight_company:
        type: string
        example: Diamond Delivery
      freight_id:
        type: string
        example: DD2020-000-0001
      freight_type_in_feet:
        type: integer
        example: 48
      max_weight_in_pounds:
        type: integer
        example: 48000
      freight_load:
        type: string
        example: LTL, Less-Than-Truck-Load
      timestamp:
        type: string
        format: date-time
        example: 2020-01-01T08:00:00.000Z